### PR TITLE
Sessions cookies

### PR DESCRIPTION
**Pull request by jc121F1**
This converts the log_in and show_user view to use session based storage for identifying the club. Other views may need to be modified.

### CODE REVIEW

**Comment by jc121F1** [comment]
Ready to merge when you guys are

**Comment by HarithAttyahKCL** [comment]
I dont spot any missed conversions to club_id, but the application_approval view has yet to be refactored to use the cookies. Not only that, after further reading, It doesnt even use a club_id since it just hits the database for all the clubs in the system and checks for the first club the request user is an Officer in. This has the side effect of a user who is the officer of two or more clubs only being able to access the applications of one. This refactoring is more significant and im not sure if we should continue on this branch or merge and then open a new pr entirely to fix it

**Comment by elcobenoz** [comment]
> I dont spot any missed conversions to club_id, but the application_approval view has yet to be refactored to use the cookies. Not only that, after further reading, It doesnt even use a club_id since it just hits the database for all the clubs in the system and checks for the first club the request user is an Officer in. This has the side effect of a user who is the officer of two or more clubs only being able to access the applications of one. This refactoring is more significant and im not sure if we should continue on this branch or merge and then open a new pr entirely to fix it

I understand the issue, it was made as I didnt have access to cookies at the time of creating the code.  I will discuss with Jack of how to get the current id of chosen club and change it accordingly, also I think we should create the change club button alongside the development of the cookies as they go hand in hand.

**Comment by jc121F1** [comment]
I think this is ready to merge once @elcobenoz adds his testing.

The club switcher story will be satisfied in a separate branch as it is a lot more extensive than I first thought.

**Pull request merged**
